- .editorconfig
- bugsnag-android-performance/build.gradle.kts
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/ContextAwareScheduledThreadPoolExecutorTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/SpanContextTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/SpanJsonTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/SpanOptionsTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/LegacyNetworkTypeTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/PerformanceLifecycleCallbacksTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/RetryDeliveryTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/RetryQueueTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SamplerTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SpanPayloadEncodingTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SpanTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SpanTrackerTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/TracePayloadTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/WorkerTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/test/OtelValidator.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/test/TestSpanFactory.kt
- build.gradle.kts
Enforce a consistent use of trailing commas when formatting with ktlint. We previously had some code with trailing commas and some without.
> Added trailing-comma rule and formatted

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/BugsnagPerformance.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/SpanOptions.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanFactory.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/SpanContextTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/SpanOptionsTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/TracerTest.kt
Rename `SpanOptions.defaults` to `SpanOptions.DEFAULTS` to make it more idiomatic to use from Java.
- Rename `SpanOptions.defaults` to `SpanOptions.DEFAULTS`
- Add more documentation comments explaining `SpanOptions.startTime`
Relied on existing tests.
> Make SpanOptions more Java friendly

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/HttpDelivery.kt
Add the `Bugsnag-Span-Sampling` header with a value of `1:0` in initial empty request
Tested manually
> Send the `Bugsnag-Sampling-Probability` header with the in initial request

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanImpl.kt
Avoid using potentially time-based randomness in the SpanId generator.
We use a single-use `SecureRandom` to generate the seed for the standard `Random` used to generate span-ids. This avoids the overheads and locks imposed by `SecureRandom` by itself, and avoids using a time-based seed.
Relied on existing tests.
> Use non-time randomness in the SpanId generator

- bugsnag-android-performance/detekt-baseline.xml
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/BugsnagPerformance.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/Connectivity.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/HttpDelivery.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/RetryDelivery.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/RetryDeliveryTask.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/Api24NetworkTypeTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/HttpDeliveryTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/RetryDeliveryTaskTest.kt
- features/fixtures/mazeracer/app/detekt-baseline.xml
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/scenarios/AppBackgroundedScenario.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/scenarios/BackgroundSpanScenario.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/scenarios/RetryScenario.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/scenarios/RetryTimeoutScenario.kt
- features/support/env.rb
If there's no connectivity, we shouldn't do a bunch of futile work like loading retries from disk or sending requests.
`Connectivity` has been enhanced to allow ad-hoc queries of the data that was only available in "network status changed" callbacks before.
`HttpDelivery` and `RetryDeliveryTask` use this to short-circuit when no connectivity is available.
Added some no-connectivity unit tests.
> [PLAT-9554] Don't attempt to send requests when there's no connectivity

- bugsnag-android-performance/detekt-baseline.xml
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/BugsnagPerformance.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/PerformanceConfiguration.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/ImmutableConfig.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/InstrumentedAppState.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/ResourceAttributes.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/ApiKeyValidationTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/ImmutableConfigTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/ResourceAttributesTest.kt
Improve and focus internal access to configuration and its defaults.
Similar to `bugsnag-android` we use an `ImmutableConfig` class which contains immutable copies of the parameters specifies by `PerformanceConfiguration` after validation and normalisation.
New unit tests added.
> Improve internal access to configuration

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/BugsnagPerformance.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/Sampler.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SamplerTask.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/Tracer.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/ProbabilitySamplerTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SamplerTaskTest.kt
- features/discarded_spans.feature
- features/fixtures/mazeracer/app/detekt-baseline.xml
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/scenarios/DisabledReleaseStageScenario.kt
Implement `enabledReleaseStages` so that spans are discarded instead of being sent, avoiding possible application behaviour if the performance SDK is not actually activated.
Abstracted the idea of "sampling" to a more generic "should this span be discarded" level. `Sampler` is now an interface with only this functionality.
When the configured `releaseStage` is not enabled the `sampler` being used is replaced with a specialised `DiscardingSampler` and the `SamplerTask` is not registered with the `Worker`. No requests are made to `Delivery` and all `Span`s are discarded instead of being sent. The SDK continues to otherwise work as expected.
A new end2end test was introduced, all other tests should continue to function as before.
> Fix enabledReleaseStages implementation

- bugsnag-android-performance/detekt-baseline.xml
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/SpanKind.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanImpl.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/SpanJsonTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SpanPayloadEncodingTest.kt
- features/manual_spans.feature
- features/okhttp_spans.feature
- features/retries.feature
Encode the `SpanKind` enums as integers in order to comply with the [OpenTelemetry JSON](https://opentelemetry.io/docs/reference/specification/protocol/otlp/#json-protobuf-encoding) spec, which states:
> Values of enum fields MUST be encoded as integer values.
This is currently the only OpenTelemetry enum that we use is `SpanKind`.
Altered existing tests to expect integer values for the `SpanKind` enum.
> Encode enums as integers to comply with OTEL specs

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/PerformanceConfiguration.kt
Allow Java code to use `PerformanceConfiguration.load` without passing an `apiKey`.
```java
PerformanceConfiguration.load(context);
```
instead of
```java
PerformanceConfiguration.load(context, null /* apiKey placeholder */);
```
> Add @JvmOverloads to PerformanceConfiguration.load

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/PerformanceConfiguration.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/ImmutableConfig.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/ImmutableConfigTest.kt
Any `releaseStage` should be considered "enabled" unless a set of `enabledReleaseStages` is explicitly set (following the standard notifier logic).
`enabledReleaseStages` can be `null` (and is by default) indicating that any `releaseStage` value is considered "enabled". This follows the same logic as `bugsnag-android`.
Added a new unit test for this behaviour
> Any releaseStage value should be considered "enabled" by default

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanChain.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanImpl.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/Tracer.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SpanChainTest.kt
Reduce the overhead of ending a `Span` by removing the locks and allocations on the "hot" side of `Span.end()`
`SpanImpl` objects can now be formed into linked-lists (type-aliased as `SpanChain` for clarity) without any external structure. When adding them to a pending batch the `Tracer` only keeps track of the most recently added `Span` instead of a traditional `Collection<Span>`. This allows us to atomically add new items, or clear the entire batch (using `getAndSet`).
- `SpanImpl` instances have an internal `next` field that allows them to be chained together (this is similar to how `android.os.Message` [sometimes works](https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/os/Message.java;l=137))
- `SpanChain` is an `internal` type alias of …
> Make ending a Span lock-free

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/PerformanceLifecycleCallbacks.kt
- features/instrumentation.feature
AppStart spans should have an attribute named `bugsnag.app_start.first_view_name` rather than `bugsnag.first_view`
Added a new check to the existing end to end tests
> Fix the name of the `first_view_name` attribute

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/BugsnagPerformance.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/PerformanceConfiguration.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/ImmutableConfig.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SendBatchTask.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/ImmutableConfigTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/ResourceAttributesTest.kt
Improve general logging and align it with `bugsnag-android`:
- Use a `NoopLogger` when `releaseStage` is "production"
- Don't log `"Sending $spanCount spans to $delivery"` messages when there are no spans actually being sent
Manually tested and added a new unit test for the configuration
> Improve logging

- Gemfile
- Gemfile.lock
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/BugsnagPerformance.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/PerformanceLifecycleCallbacks.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanTracker.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/ViewLifecyclePhase.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/ViewLoadPhase.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/PerformanceLifecycleCallbacksTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SpanTrackerTest.kt
- features/instrumentation.feature
- features/support/env.rb
Adds automatic instrumentation for the `onCreate` `onStart` and `onResume` phases of an activity load
On >= Android 10 (API level 29) the pre/post callbacks of ActivityLifecycleCallbacks are used to start and end spans for each of the Activity lifecycle phases `onCreate` `onStart` and `onResume`.
These spans are nested under a `ViewLoad` span for the `Activity`, and are not created if `autoInstrumentActivities = AutoInstrument.OFF`
- Added new unit tests for the new lifecycle callback implementation 
- Bumped maze-runner to latest (v7.23.0) - this allows us to test for spans with a particular name and set of attributes
- Extended the end to end instrumentation tests to cover new functionality
> feat(activity): added activity load phase instrumentation

- bugsnag-plugin-android-performance-coroutines/src/main/kotlin/com/bugsnag/android/performance/coroutines/BugsnagPerformanceCoroutines.kt
- features/fixtures/mazeracer/app/build.gradle
- features/fixtures/mazeracer/app/proguard-rules.pro
- features/fixtures/mazeracer/app/src/main/AndroidManifest.xml
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/NestedSpansActivity.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/scenarios/NestedSpansScenario.kt
- features/fixtures/mazeracer/app/src/main/res/layout/fragment_1.xml
- features/fixtures/mazeracer/app/src/main/res/layout/fragment_2.xml
- features/nested_spans.feature
Adds a new e2e scenario to test nested spans and coroutine support.
The scenario does a bunch of things such as:
- launches an activity with full view load instrumentation
- loads some Fragments
- creates some custom spans
- starts some coroutines
The test checks that all of the expected spans are received and that spans are correctly nested under the expected parent span
> Add test scenario for nested spans and coroutines

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/Tracer.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/TracerTest.kt
Avoid emitting null-pointer exceptions as warnings when there is no batch to be collected
Added a new unit test to cover this case
> Correctly handle null batches

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/Connectivity.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/ConnectivityLegacyTest.kt
Map the non-OpenTelemetry network subtypes to known values.
New unit test covering various expected mappings from `ConnectivityLegacyTest`
> Add mapping for non-otel network subtypes

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/NetworkRequestAttributes.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/HttpDelivery.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/NetworkRequestAttributesTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/SpanJsonTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/SpanOptionsTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/PerformanceLifecycleCallbacksTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/RetryDeliveryTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SendBatchTaskTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SpanChainTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SpanPayloadEncodingTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SpanTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SpanTrackerTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/TracePayloadTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/test/NoopSpanProcessor.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/test/TestUtils.kt
- bugsnag-plugin-android-performance-okhttp/src/main/kotlin/com/bugsnag/android/performance/okhttp/BugsnagPerformanceOkhttp.kt
Allow manually instrumented network requests to set HTTP related attributes on the `Span` without reaching into the `internal` APIs.
Added a new `NetworkRequestAttributes` object with utility methods for each of the "NetworkRequest" attributes currently supported. Each of these methods accepts a `Span` and the value of the attribute to set.
The approach was used in favour of dedicated types (such as `NetworkRequestSpan`) as those would likely become an obsolete concept fairly quickly. The `NetworkRequestAttributes` object will also make a convenient container for the actual attribute constants when we allow arbitrary attributes to be specified.
Extension functions were avoided as it was found they either become verbose to use (`span.setNetworkRequestResponseCode`) or ambiguous (as they …
> Network request attributes

- .buildkite/pipeline.yml
- docker-compose.yml
- features/fixtures/mazeracer/app/detekt-baseline.xml
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/MainActivity.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/MazeRacerApplication.kt
- features/steps/performance_steps.rb
Migrates the Android 13 e2e tests to BitBar.
Follows the pattern used in other repos and in particular takes the test fixture code needed to determine the public AWS address directly from bugsnag-android. 
Covered by CI.
> Move Android 13 e2e tests to BitBar

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/SpanOptions.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanCategory.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanContextExtensions.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanFactory.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanImpl.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/Worker.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/SpanContextTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/SpanJsonTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/SpanOptionsTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/RetryDeliveryTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SpanPayloadEncodingTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SpanTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/test/TestSpanFactory.kt
- features/nested_spans.feature
Only the first `ViewLoad` span in a SpanContext should be considered "first class", and the first "ViewLoad" span in a `SpanContext` should be first class by default.
- *Breaking change*: `SpanOptions.isFirstClass` is now a nullable `Boolean?` (`Boolean` in Java instead of `boolean`) and will default to `null` instead of attempting to derive a global default
- `SpanImpl` now tracks the `SpanCategory` (VIEW_LOAD, NETWORK, etc.) as an enum property, instead of just an attribute
- `SpanFactory.createViewLoadSpan` will search for existing `SpanCategory.VIEW_LOAD` spans when deciding on a default value for `isFirstClass`
- `SpanFactory.createCustomSpan` retains the previous behaviour (first span on the context is first class)
New unit test for this specific behaviour.
Modified existing tests, …
> Only first ViewLoad in context should be first-class

- CHANGELOG.md
- bugsnag-android-performance/detekt-baseline.xml
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/BugsnagPerformance.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/Connectivity.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/ContextExtensions.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/Api24NetworkTypeTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/ConnectivityLegacyTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/HttpDeliveryTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/LegacyNetworkTypeTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/RetryDeliveryTaskTest.kt
- examples/performance-example/app/src/main/AndroidManifest.xml
Ensure that the network subtype is reported when available, and of a known type. Simplify the reporting to reduce possible bugs.
Encapsulated all of the network status into a new immutable `ConnectivityStatus` class. Flattened the `Connectivity` delegation layers, and merged the event-handling logic with the information retrieval such that using `Connectivity.connectionStatus` and receiving a `NetworkChangeCallback` use the exact same construction logic.
Relied on existing end-to-end tests, and updated the existing unit tests. Tested the in-app / on-device behaviour manually.
> Improve the reporting of the network subtype

- .buildkite/pipeline.yml
Make the build pipeline more efficient by only uploading the test fixture once.
I've also implemented the use of Buildkite matrices, saving several repetitive lines of YAML.
Covered by CI.
> Only upload test fixture once

- CHANGELOG.md
- bugsnag-plugin-android-performance-okhttp/src/main/kotlin/com/bugsnag/android/performance/okhttp/BugsnagPerformanceOkhttp.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/scenarios/OkhttpSpanScenario.kt
- features/okhttp_spans.feature
Don't report metrics for failed and cancelled network requests.
New end-to-end scenario
> Discard failed network request spans

- CHANGELOG.md
- bugsnag-android-performance/detekt-baseline.xml
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/BugsnagClock.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/BugsnagClockTest.kt
Detect obvious clock problems when calculating the boot time, and work around them
When starting up attempt to use the GNSS clock source (when available) as a way to fix the boot-time, and fallback to using the wall time. In both cases we detect negatives as invalid, eventually falling back to a `0` boot time.
Manual testing for the GNSS clock, and unit tests for the fallback
> Attempt to use more reliable clock fixes

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/BugsnagClock.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/DateUtils.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/HttpDelivery.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/HttpDeliveryTest.kt
- features/manual_spans.feature
Introduce a `Bugsnag-Sent-At` header to all requests to allow the server to adjust the time (in case of skew device clocks).
Used the `BugsnagClock` to ensure that the `Bugsnag-Sent-At` header is consistent with the timestamps delivered in the spans.
New unit tests added, along with a new check in the existing end-to-end scenarios
> Add `Bugsnag-Sent-At` header to all requests

- LICENSE
- README.md
Updated readme with proposed standard header (in the SmartBear asset library).
It works using a media query for light and dark mode, however not all IDEs support this so the light mode image uses a white (as opposed to transparent) background so that it is a visible version whatever the theme.
For some reason VSCode uses the theme of the system and what the editor itself is using - this means you don't see the effect if you just switch theme in the editor, but it works if you switch OS theme.
> docs(readme): update branding

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/Connectivity.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/ConnectivityLegacyTest.kt
Map "CDMA - 1xRTT" network subtype on legacy devices to the expected "cdma2000_1xrtt" value
Added to existing unit tests
> Map "CDMA - 1xRTT" network subtype to the expected "cdma2000_1xrtt" value

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/BugsnagPerformance.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/InstrumentedAppState.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/PerformanceLifecycleCallbacks.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanFactory.kt
- features/fixtures/mazeracer/app/detekt-baseline.xml
- features/fixtures/mazeracer/app/src/main/AndroidManifest.xml
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/MazeRacerAlarmReceiver.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/MazeRacerApplication.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/scenarios/ActivityLoadInstrumentationScenario.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/scenarios/BackgroundAppStartScenario.kt
- features/instrumentation.feature
- features/nested_spans.feature
Avoid logging background AppStarts due to broadcasts or service starts that are not user perceivable by discarding any `AppStart` span that doesn't have a nested `Activity` start within a reasonable time limit.
This PR includes the following changes:
- A property rename from `platformCallbacks` to `activityCallbacks` for clarity
- A timeout of 1 second between the start of `AppStart` and the expected `onCreate` of the first `Activity` (after this the `AppStart` is discarded)
- A change to the `AppStart` options to that it never has a parent-span
Added a new end-to-end scenario that uses the `AlarmManager` to trigger a broadcast to restart the app without starting an `Activity`.
> Discard background AppStart

- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/MainActivity.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/Scenario.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/scenarios/ActivityLoadInstrumentationScenario.kt
Improve the reliability of the ViewLoad auto instrumentation tests by controlling when the batch is flushed using the instrumentation directly.
Added a new function that will cause `MainActivity.finish()` when another selected `Activity` finishes (in this case the `ActivityViewLoadActivity` that we use for instrumentation testing).
By `finish`in the `MainActivity` the SDK will trigger a background-flush of the current span batch (after other instrumentation is completed).
Instrumentation tests now pass more reliably.
> Force test fixture to background to flush

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/PerformanceLifecycleCallbacks.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanCategory.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanFactory.kt
Normalise the creation of ViewLoadPhase spans by adding a new function to `SpanFactory` instead of using `createCustomSpan`.
> Restructured ViewLoadPhase spans to use SpanFactory

- CHANGELOG.md
- bugsnag-android-performance/detekt-baseline.xml
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/BugsnagPerformance.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/DefaultAttributeSource.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/DeviceIdFilePersistence.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/Worker.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/WorkerTest.kt
- features/manual_spans.feature
Report an app-unique `device.id` as a resource level attribute. Where possible it should be the same as `bugsnag-android` will report.
Introduced the `DeviceIdFilePersistence` largely mirrored from `bugsnag-android` which runs 
Added a check for the attribute on an existing end-to-end test. Manually tested `bugsnag-android` & `bugsnag-android-performance` reporting the same ID in a single app.
> Add `device.id` as a resource-level attribute

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/BugsnagPerformance.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/PerformanceLifecycleCallbacks.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanFactory.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanImpl.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanTracker.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/PerformanceLifecycleCallbacksTest.kt
- bugsnag-plugin-android-performance-okhttp/src/main/kotlin/com/bugsnag/android/performance/okhttp/BugsnagPerformanceOkhttp.kt
- examples/performance-example/app/src/main/java/com/example/bugsnag/performance/MainActivity.kt
- features/fixtures/mazeracer/app/detekt-baseline.xml
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/ActivityViewLoadActivity.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/DebugLogger.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/MainActivity.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/scenarios/ViewLoadLeakScenario.kt
- features/instrumentation.feature
Generally cleanup some of the Span creation & tracking to reduce the possibility of bugs or edge cases.
- `Activity` associated `ViewLoad` spans are now considered "leaked" if `onStop` is called before they are ended
- The trace id validity check in `SpanFactory` has been fixed to only consider `0` as invalid
- `SpanImpl` objects can be formally "discarded" (marking them as ended without enqueuing them) which helps ensure that they don't leak
- `Activity` lifecycle is now tracked more effectively
- calls to `finish()` in `onCreate` no longer leak ViewLoad spans
- each ViewLoadPhase will ensure it's predecessor is closed
- Added an end-to-end test for the ViewLoad span leaking behavior.
> General Span cleanup

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/PerformanceConfiguration.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/ConfigurationLoaderTest.kt
Allow `apiKey` and `enabledReleaseStages` to be configured in the manifest file, separately to the options used by `bugsnag-android`.
New unit tests for both namespaces, and the overrides
> Allow apiKey + enabledReleaseStages to be configured in Manifest

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/BugsnagPerformance.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/PerformanceLifecycleCallbacks.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanFactory.kt
- features/nested_spans.feature
The `AppStart` span should be ended when the first `ViewLoad` span is ended.
We only track this against `ViewLoad` spans associated with `Activity` objects, as these are the only `ViewLoad` spans we can reasonably track against `AppStart` without risking leaking the `AppStart` spans.
Modified the end-to-end tests to check the span end times.
> Moved the end of AppStart spans to the end of the first ViewLoad span

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/SpanContext.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/Internals.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/PerformanceLifecycleCallbacks.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanFactory.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanImpl.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/ViewLoadPhase.kt
- bugsnag-plugin-android-performance-appcompat/src/main/kotlin/com/bugsnag/android/performance/AppCompatModule.kt
- bugsnag-plugin-android-performance-appcompat/src/main/kotlin/com/bugsnag/android/performance/BugsnagPerformanceExt.kt
- bugsnag-plugin-android-performance-appcompat/src/main/kotlin/com/bugsnag/android/performance/FragmentActivityLifecycleCallbacks.kt
- bugsnag-plugin-android-performance-appcompat/src/test/kotlin/com/bugsnag/android/performance/FragmentActivityLifecycleCallbacksTest.kt
- bugsnag-plugin-android-performance-coroutines/src/main/kotlin/com/bugsnag/android/performance/coroutines/BugsnagPerformanceCoroutines.kt
- bugsnag-plugin-android-performance-coroutines/src/test/java/com/bugsnag/android/performance/coroutines/BugsnagPerformanceCoroutineTest.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/NestedSpansActivity.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/scenarios/NestedSpansScenario.kt
- features/nested_spans.feature
When adding more than one `Fragment` in a single transaction the `ViewLoad` spans should not nest when the `Fragments` are "parallel" (ie: not parent/child).
`ViewLoad` spans for `Fragment` are no longer set as the current context, and instead a new `ViewLoadPhase/FragmentCreate` is created to encapsulate the creation spans.
The `ViewLoad` still runs from pre-create -> post-resume.
Manual testing and a new unit test
> Fragment ViewLoads should not nest unexpectedly

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/BugsnagPerformance.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/AppStartPhase.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/InstrumentedAppState.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/PerformanceLifecycleCallbacks.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanCategory.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanFactory.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanTracker.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/processing/ForwardingSpanProcessor.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/processing/ForwardingSpanProcessorTest.kt
- features/fixtures/mazeracer/app/detekt-baseline.xml
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/scenarios/AppStartScenario.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/scenarios/PreStartSpansScenario.kt
- features/instrumentation.feature
- features/nested_spans.feature
Introduce `AppStartPhase/Framework` as the time between class-loading and `Application.onCreate`
`BugsnagPerformance.reportApplicationClassLoaded` will now open a secondary `AppStartPhase/Framework` nested span under `AppStart` which will be closed when `BugsnagPerformance.start` is called.
This is not a perfect measurement as:
- `reportApplicationClassLoaded` may not be called
- `reportApplicationClassLoaded` does not exactly represent when the process started
- `BugsnagPerformance.start` may be called late in `Application.onCreate`
- `BugsnagPerformance.start` may be called from an `Activity` or similar
As such the measurement does not currently exactly match its description, however our next step will be 
Modified the existing end-to-end tests to cover the new span.
> Introduce AppStartPhase/Framework

- CHANGELOG.md
- bugsnag-plugin-android-performance-okhttp/src/main/kotlin/com/bugsnag/android/performance/okhttp/BugsnagPerformanceOkhttp.kt
- features/fixtures/mazeracer/app/build.gradle
Support okhttp 5.0.0
Replaced the use of the internal okhttp `headersContentLength()` utility function with a direct implementation
Modified the test fixture to use okhttp 5.0.0-alpha11 (latest version at time of writing).
> Support okhttp 5.0.0

- CHANGELOG.md
- bugsnag-android-performance/detekt-baseline.xml
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/Connectivity.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/HttpDelivery.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/Api24NetworkTypeTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/ConnectivityLegacyTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/LegacyNetworkTypeTest.kt
When there is no active network traces should be queued and retried as expected.
Categorize `IOException` as failed-with-retry instead of propagating the exception.
Categorize a lack of network connectivity as "UNAVAILABLE" instead of "UNKNOWN" to avoid infinite retries when there is no active network.
All connectivity changed events now update the connectivity state based on the "active" network instead of the network that is changing status.
Updated unit tests and manually tested.
> Fix connectivity / retry

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/BugsnagPerformance.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/NetworkRequestInfo.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/NetworkRequestInstrumentationCallback.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/PerformanceConfiguration.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/ImmutableConfig.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/InstrumentedAppState.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/NetworkRequestInfo.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanFactory.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/ResourceAttributesTest.kt
- bugsnag-plugin-android-performance-okhttp/src/main/kotlin/com/bugsnag/android/performance/okhttp/BugsnagPerformanceOkhttp.kt
- features/fixtures/mazeracer/app/detekt-baseline.xml
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/scenarios/OkhttpAutoInstrumentNetworkCallbackScenario.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/scenarios/OkhttpManualNetworkCallbackScenario.kt
- features/okhttp_spans.feature
URLs in network request spans can now be customized via configurable callback.
Per ED
New e2e tests to verify automatic and manual span creation.
> [PLAT-10773] Add support for network span URL customization via callbacks

- bugsnag-android-performance/detekt-baseline.xml
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/ActivityControl.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/AutoInstrumentationCache.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/AutoInstrumentationCacheTest.kt
An automation to tell if the fragment or activity needs to ended instrumentation or ended app start
Add automation class to tell if the fragment or activity needs to ended instrumentation or ended app start by the cache
Introducing new unit tests
> Implement instrumentation configuration cache

- features/fixtures/mazeracer/app/detekt-baseline.xml
- features/fixtures/mazeracer/app/src/main/AndroidManifest.xml
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/SplashScreenActivity.kt
- features/instrumentation.feature
- features/nested_spans.feature
- features/steps/performance_steps.rb
End to end tests for a splash activity which is annotated as DoesNotEndAppStart and ensure that the end time of the AppStart is equal to the end of ViewLoad from a main activity.
> End to end tests for DoNotEndAppStart class

- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/MainActivity.kt
- features/server_response_pvalue.feature
Make the server_response_pvalue tests pass more reliably.
- Corrected the `notify` / `sessions` endpoint config for the `bugsnag-android` config in the end-to-end fixture
- Slightly adjusted the "Update P to 0 on second response: fail-retriable, fail-permanent, success" test scenario
Tests should pass more reliably now.
> Make the server_response_pvalue tests pass more reliably

- CHANGELOG.md
- bugsnag-plugin-android-performance-coroutines/src/main/kotlin/com/bugsnag/android/performance/coroutines/BugsnagPerformanceCoroutines.kt
- bugsnag-plugin-android-performance-coroutines/src/test/java/com/bugsnag/android/performance/coroutines/ContextAwareCoroutineContextElementTest.kt
Ensure that spans measured within child coroutines of measured coroutines nest as expected.
Introduce a `BugsnagCoroutineContext` to handle copying the `SpanContext` stack when child coroutines are forked (using `async` or `launch` from within a coroutine).
This avoids the currently experimental & delicate `CopyableThreadContextElement` API which is still subject to change, but also only works if the initial `coroutineContext` is derived from a `BugsnagPerformanceScope`.
A new unit test was introduced to assert the expected nesting of spans, including a second-level nested span within the child coroutines.
> Fix child coroutine span nesting

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/instrumentation/ActivityLifecycleInstrumentation.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/instrumentation/HotStartTest.kt
Ensure that Activity ViewLoad spans are nested under their expected AppStart/Warm / AppStart/Hot spans (when applicable).
New unit tests added to ensure the expected span parentage.
> Fix Warm/Hot Activity / AppStart span ordering

- .buildkite/pipeline.yml
Reduce test flakes by setting Appium capabilities to identify the correct start Activity.
The e2e test fixture contains multiple Activity classes, which can confuse Appium when it tries to launch the app,.  This change ensures that Appium uses the correct Activity to detect that the app has started.
Before this change the following error was seen at least one in ten times:
```
Cannot start the 'com.bugsnag.mazeracer' application. 
```
After the change the error wasn't seen once in 60 attempts.
> Set Appium capabilities to be sure of selecting correct start Activity

- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/MainActivity.kt
This fixes a bunch of flakes where the test fixture couldn't pull the next command from maze-runner due to not having the correct UUID when requesting it.
> Persist the command UUID between app restarts when testing

- CHANGELOG.md
- bugsnag-android-performance/detekt-baseline.xml
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/instrumentation/ActivityLifecycleInstrumentation.kt
Auto-instrumented spans should only be considered “leaked” when the `Activity` is destroyed, since the `Activity` may stop and restart while the span is still valid (for example when backgrounded briefly).
Removed `onViewLoadLeak` from `Activity.onStop` instrumentation
> Removed onViewLoadLeak trigger for Activity.onStop

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/Sampler.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanImpl.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/ProbabilitySamplerTest.kt
The `Span.samplingProbability` should only be changed if the new probability is strictly less-than the current span probability.
Introduced new unit tests to cover the expected behavior.
> Correctly reassign the Span samplingProbability

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanImpl.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/SpanJsonTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SpanPayloadEncodingTest.kt
Ensure every span reports it's `samplingProbability` again
Ensure that the `SpanImpl.samplingProbability` setter is called at least once (in the `init` block)
> Ensure that the sampling probably is included correctly

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanImpl.kt
- bugsnag-plugin-android-performance-okhttp/src/main/kotlin/com/bugsnag/android/performance/okhttp/BugsnagPerformanceOkhttp.kt
Introduce a function to return the content of the traceparent header and a function base on given `SpanImpl` `samplingProbability` and `samplingValue` to determine if the span is sampled.
Added `isSampled()` to `SpanImpl`  and  `buildTraceparentHeader()` to `BugsnagPerformanceOkhttp`
> Build traceparent header from span impl

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/BugsnagPerformance.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/InstrumentedAppState.kt
- bugsnag-plugin-android-performance-okhttp/consumer-rules.pro
- bugsnag-plugin-android-performance-okhttp/src/main/kotlin/com/bugsnag/android/performance/okhttp/OkhttpModule.kt
Make is easier for the `BugsnagPerformanceOkhttp` class to access its configuration by introducing an `OkhttpModule`.
Manual testing to see that the new module is loaded as expected.
> Add OkHttpModule to share cross-module config

- .buildkite/pipeline.yml
Updates all buildkite steps running on MacOS 12 to MacOS 14.  Note - once this is merged I'll also update the default pipeline step to MacOS 14.
> Update Buildkite macos 12 steps to run on macos 14

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanImpl.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanTracker.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/TracePayload.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/instrumentation/ActivityLifecycleInstrumentation.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/AppStartTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SpanPayloadEncodingTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SpanTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SpanTrackerTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/instrumentation/ActivityLifecycleInstrumentationTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/instrumentation/LegacyActivityInstrumentationTest.kt
Optimised  updating end time for span by using `AtomicLong`
Replace `AtomicLongFieldUpdater` with `AtomicLong` to update end time in `spanImpl`
Existing tests
> Update Span end time with AtomicLong 

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/SpanOptions.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanFactory.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/instrumentation/ActivityLifecycleInstrumentation.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/SpanOptionsTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/processing/TracerTest.kt
- bugsnag-plugin-android-performance-appcompat/src/main/kotlin/com/bugsnag/android/performance/FragmentActivityLifecycleCallbacks.kt
- bugsnag-plugin-android-performance-okhttp/src/main/kotlin/com/bugsnag/android/performance/okhttp/BugsnagPerformanceOkhttp.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/MazeRacerAlarmReceiver.kt
Introduce easier factory functions to create `SpanOptions` to improve the usage syntax.
Introduce factory functions (which line-up with existing instance function names) for `SpanOptions`:
| Kotlin                          | Java                                     |
| --------------------- | -------------------------- |
| `SpanOptions.within`| `SpanOptions.createWithin` |
| `SpanOptions.startTime` | `SpanOptions.createWithStartTime` |
| `SpanOptions.makeCurrentContext` | `SpanOptions.createAsCurrentContext` |
| `SpanOptions.setFirstClass` | `SpanOptions.createFirstClass` |
The new syntax is optional, and simply a convenience over the existing `SpanOptions.DEFAULTS.****` calls.
Existing tests
> Easier creation of SpanOptions

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanImpl.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/instrumentation/ActivityLifecycleInstrumentation.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/instrumentation/ForegroundState.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/instrumentation/ActivityLifecycleInstrumentationTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/instrumentation/LegacyActivityInstrumentationTest.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/scenarios/DiscardViewLoadOnStopScenario.kt
- features/instrumentation.feature
When app is in the background, viewLoad does not inflate the aggregate metrics
Added method in onPaused to discard all the span 
Unit tests and manual testing in example app
> Discard unclosed ViewLoad spans when Activity  is paused

- CHANGELOG.md
- bugsnag-android-performance/build.gradle.kts
- bugsnag-android-performance/detekt-baseline.xml
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/BugsnagPerformance.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanFactory.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanImpl.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/integration/NotifierIntegration.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/integration/NotifierIntegrationTest.kt
- gradle/libs.versions.toml
Link `Event`s reported by [bugsnag-android](https://github.com/bugsnag/bugsnag-android/) with the currently active `SpanContext`.
The new `NotifierIntegration` object is `link`ed on startup, and will attempt to check if `Bugsnag` exists and is started. If either the class cannot be loaded (signified by a `NoClassDefError`) or are `Bugsnag` is not started the `NotifierIntegration` marks itself as unlinked, and takes no further actions.
Otherwise (via an [OnErrorCallback](http://bugsnag.github.io/bugsnag-android/bugsnag-android-core/com.bugsnag.android/-on-error-callback/index.html)) the current `SpanContext` is attached to the `Event` via the new `setTraceCorrelation` function.
Manually tested with an app, and in a new unit test.
> Add the current span/trace to Events in bugsnag-android

- bugsnag-android-performance/detekt-baseline.xml
- features/nested_spans.feature
- features/server_response.feature
To reduce the complexity in server_response and make it into simple two scenarios
Replace scenario with one fail-permanent and one with fail-retriable and then fail-permanent
Update the existing current end to end tests
> Replace server_response.feature with 2 scenarios

- features/server_response.feature
- features/server_response_pvalue.feature
Reduce flakeyness in the server response code/probability tests - again
Reordered the HTTP response steps so that the selected status codes always only apply to the expected traces.
> Reduce flakeyness in the server response code/probability tests

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/Attributes.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/HasAttributes.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/Attributes.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/AttributesJson.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/Delivery.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/DeviceIdFilePersistence.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/HttpDelivery.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/ResourceAttributes.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/RetryDelivery.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SendBatchTask.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanImpl.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/TracePayload.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/NetworkRequestAttributesTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/SpanContextTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/SpanOptionsTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/HttpDeliveryTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/ResourceAttributesTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/RetryDeliveryTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SendBatchTaskTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SpanPayloadEncodingTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/TracePayloadTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/test/StubDelivery.kt
Reduce the API surface and implementation of `Attributes` and `HasAttributes` before they are surfaced as officially public API.
The original `Attributes` class and `HasAttributes` interface were too tightly coupled, and exposed API that forces additional overheads (converting `Map.Entry` -> `Pair`) with no gain.
This PR reduces the visibility of the `Attributes` implementation, allowing us to make more significant changes later on without breaking changes.
The `Attributes` and `HasAttributes` were both previously public API, but there is no public way to access them currently. This PR aims to reduce the probability that any future breaking changes will be needed.
- `Attributes` no longer implements `Collection<Pair<String, Any>>` which reduces the iteration overhead when writing them as …
> Reduce the scope of the Attributes / HasAttributes

- CHANGELOG.md
- bugsnag-android-performance/detekt-baseline.xml
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/Connectivity.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/ContextExtensions.kt
Capturing the exception when getting NetworkCapabilities
Added a `safeGetNetworkCapabilities` which will capture the security exception when `ConnectivityManager` is getting network capabilities
> capturing Security exception on Android 

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/framerate/FramerateCollector.kt
If the OS does not consider a frame to be slow or frozen, we should not report it as such.
Relied on existing testing.
> Only consider a frame as slow or frozen if it missed its deadline

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/InstrumentedAppState.kt
Store and expose the finalised `ImmutableConfig` so that it is accessible from Java. This is not used anywhere internally but is required for the upcoming React Native integration
Added a new `config` property in `InstrumentedAppState` - this will return `null` if `InstrumentedAppState.configure` (and therefore `BugsnagPerformance.start`) has not been called.
This isn't used anywhere yet, but tested manually from a React Native Turbo module
> Expose finalised config via `InstrumentedAppState`

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/BugsnagPerformance.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/AppStartTracker.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/InstrumentedAppState.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/instrumentation/ActivityLifecycleInstrumentation.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/scenarios/AppStartDisabledScenario.kt
- features/instrumentation.feature
- features/steps/performance_steps.rb
Avoid over-reporting warm starts.
Correctly report the backgrounding of the app to the `AppStartTracker`
Manually tested and a new end to end test to check the behavior when `autoInstrumentAppStarts = false`
> Only report warm appstarts when the app was properly backgrounded

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/HttpDelivery.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/MazeRacerApplication.kt
Fix https://github.com/bugsnag/bugsnag-android-performance/issues/297 by tagging the socket in the same way as we do in the notifier.
Modified the end to end test fixture to treat any networking StrictMode violation as fatal. A later PR will change to `detectAll` to cover all other StrictMode violations.
> Fix Untagged socket violation in HttpDelivery

- dockerfiles/Dockerfile.android-publisher
Add `bugsnag-plugin-android-performance-compose` to the modules in the CI publishing container.
> Add compose to the list of published modules

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/Attributes.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanFactory.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanImpl.kt
Allow external systems to create spans and access start times and attributes on created spans
Adds JVM annotations to `SpanFactory.createCustomSpan`, `SpanImpl.startTime` and `Attributes.entries`
Tested manually
> Expose span creation, start times and attribute entries to Java

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/BugsnagClock.kt
Adds a utility function to `BugsnagClock` to convert a given time from Unix time with nanosecond precision into `SystemClock.elapsedRealtimeNanos`.
This allows external systems to specify start and end times relative to the internal clock.
> Support converting unix nanoseconds to elapsedRealtimeNanos

- .buildkite/pipeline.yml
Explicitly state the default Buildkite queue, rather than rely on the queue configure in the Buildkite UI itself.
Covered by CI.
> Explicitly state default Buildkite queue

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanImpl.kt
Split the span ending and processing logic for first-party modules.
> Split up the span ending and processing

- .github/workflows/signing.yml
Restricts the permissions the signing workflow token has to read only.
> Add restrictions on default github token access

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanImpl.kt
Allow external modules to read the end time on created spans
> Make `SpanImpl.endTime` accessible from Java

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/BugsnagPerformance.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/Worker.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/WorkerTest.kt
- features/fixtures/mazeracer/app/detekt-baseline.xml
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/Log.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/MainActivity.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/MazeRacerAlarmReceiver.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/MazeRacerApplication.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/PerformanceTestUtils.java
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/Scenario.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/StartupConfiguration.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/scenarios/AppStartDisabledScenario.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/scenarios/AppStartScenario.kt
- features/fixtures/mazeracer/app/src/main/java/com/bugsnag/mazeracer/scenarios/BackgroundAppStartScenario.kt
Move all startup I/O to the background worker thread and avoid StrictMode disk access violations.
Replaced the list of `startupTasks` in the `Worker` with a single lambda function which is called to create the list of `Task` objects that the `Worker` needs to run.
This effectively moves most of the `BugsnagPerformance.start` implementation to the background worker thread, along with the construction of the `Persistence` class and all the I/O required.
Added `StrictMode.ThreadPolicy.detectAll()` to the MazeRunner fixture, and modified the test fixture & scenarios to avoid `StrictMode` violations. Most significantly `Scenario` now implements `CoroutineScope` to make it easier for scenarios that rely on disk I/O to save/load data on an `IO` thread instead of the main thread.
> Strict mode fixes

- .github/workflows/scorecard.yml
Bump the version of the `upload-artifact` action for SSF Scorecard to latest to avoid sunsetting of v3.
> build(scorecard): bump upload action

- bugsnag-android-performance/detekt-baseline.xml
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanFactory.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanImpl.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/framerate/FramerateMetricsSource.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/metrics/MetricSource.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/metrics/SpanMetricsSnapshot.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SpanFactoryTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SpanStateTest.kt
Allow for multiple metrics per span, by abstracting Span Metrics out of `SpanImpl`
Created a new `SpanMetrics` class which serves as a container for the `MetricsSource`s and snapshots applicable to a given span.
- added the `SpanMetrics` container class
- updated `SpanState` to allow spans to be blocked *during* `end()` (by metrics or integrations)
New tests added for the `SpanState` to check all of its state flows, updated existing tests to handle the change from frame metrics -> span metrics
> Abstract Span Metrics out of SpanImpl

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/util/FixedRingBuffer.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/util/FixedRingBufferTest.kt
Implement a fixed-size data structure (ring buffer in this case) for storing metrics samples for later attaching to spans.
New unit tests added
> Add buffer to store metrics samples

- bugsnag-android-performance/detekt-baseline.xml
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanFactory.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/processing/SpanTaskWorker.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/processing/Timeout.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/processing/SpanTaskWorkerTest.kt
Refactor the Condition timeout thread (previously `TimeoutExecutorImpl`) as a more generic worker capable of handling both the timeouts, and regular sampling tasks.
Added new unit test coverage of the additional functionality.
> Span Task Worker Thread

- bugsnag-android-performance/detekt-baseline.xml
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/EnabledMetrics.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/PerformanceConfiguration.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/SpanMetrics.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/SpanOptions.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/InstrumentedAppState.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/processing/ImmutableConfig.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/ImmutableConfigTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/ResourceAttributesTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SpanFactoryTest.kt
Introduce device metrics configuration options to allow configuration of rendering, cpu and memory metrics capturing and reporting.
- Add `EnableMetrics` to `PerformanceConfiguration` and `SpanMetrics` to `SpanOptions`. Both metrics class contain rendering, CPU and memory enable options allowing either global or per-span configuration.
- Deprecated the older `instrumentRendering` configuration options (with suggested replacements).
Updated existing tests to use the new options
> metrics option added to configuration and span options

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/BugsnagPerformance.kt
Clarify what `BugsnagPerformance.reportApplicationClassLoaded` does and how/when/where it should be used.
> Improve docs for reportApplicationClassLoaded

- CHANGELOG.md
- bugsnag-plugin-android-performance-compose/detekt-baseline.xml
- bugsnag-plugin-android-performance-compose/src/androidTest/java/com/bugsnag/android/performance/BugsnagPerformanceHooks.java
- bugsnag-plugin-android-performance-compose/src/androidTest/java/com/bugsnag/android/performance/BugsnagPerformanceTestingExtensions.kt
- bugsnag-plugin-android-performance-compose/src/androidTest/java/com/bugsnag/android/performance/compose/LoadingIndicatorTest.kt
- bugsnag-plugin-android-performance-compose/src/androidTest/java/com/bugsnag/android/performance/compose/MeasuredComposableTest.kt
- bugsnag-plugin-android-performance-compose/src/main/java/com/bugsnag/android/performance/compose/LoadingIndicator.kt
Allow Compose UIs to easily mark their real "loading time" using a simple `LoadingIndicator` composable.
As long as at least one `LoadingIndicator` is part of composition any active ViewLoad will remain open. Once all `LoadingIndicator`s have been disposed the `ViewLoad` ends at the timestamp of the last disposal.
Manual testing and a new unit test
> Add LoadingIndicator composable

- .github/dependabot.yml
- .github/workflows/scorecard.yml
- .github/workflows/signing.yml
Adds dependabot config to raise PRs for bundler and GHA. Also pins remaining GHA dependencies.
> build: add dependabot config for dependency updates and pin existing GHA

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/InstrumentedAppState.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanFactory.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/metrics/AbstractSampledMetricsSource.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/metrics/MemoryMetricsSource.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/metrics/SpanMetricsSnapshot.kt
- features/frame_metrics.feature
Add sampled memory metrics to all `firstClass` spans.
Added the new `MemoryMetricsSource`  at a fixed interval (1 second) and adds all relevant Memory android run time use and device use to all `firstClass` spans.
Updated existing end-to-end tests to expect memory metrics.
> memory metrics

- features/steps/performance_steps.rb
Use the Maze Runner Appium API instead of `Maze.driver` directly, so that failed Appium drivers are detected and reported.
Covered by CI.
> Use Maze Runner Appium API

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/metrics/CpuMetricsSource.kt
- features/device_metrics.feature
The CPU metrics had some properties named `bugsnag.metrics.*` instead of the expected `bugsnag.system.*`
Manual testing and updated the end-to-end tests
> Fix the CPU metrics property names

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/metrics/CpuMetricsSource.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/metrics/MemoryMetricsSource.kt
When capturing the "starting point" for CPU or Memory metrics, we need to capture the sample taken before the span is opened.
Relied on existing end-to-end tests passing consistently (where they previously flaked due to timing)
> Fix off-by-one error in Device metrics

- features/instrumentation.feature
- features/manual_spans.feature
- features/okhttp_spans.feature
Stop using deprecated Cucumber step.
The step used instead is functionally equivalent - expecting at least the number of spans given.  The replace step will be removed in the next major version of Maze Runner.
Covered by CI.
> Stop using deprecated Cucumber step

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/BugsnagPerformance.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/RemoteSpanContext.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/Encodings.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/Sampler.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanFactory.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/RemoteSpanContextTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/SpanFactoryTest.kt
- bugsnag-plugin-android-performance-okhttp/src/main/kotlin/com/bugsnag/android/performance/okhttp/BugsnagPerformanceOkhttp.kt
Allow easy cross-layer span parenting so that spans can be nested under spans from remote servers or non-native app layers (such as JavaScript in a WebView).
Introduced the new `RemoteSpanContext` class that encapsulates encoding & parsing of `SpanContext`s in the `traceparent` header format. The encoding can be applied to any `SpanContext` object, and the strings can be parsed into `RemoteSpanContext` objects.
New unit tests added
> Allow easy cross-layer span parenting

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/BugsnagPerformance.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/controls/SpanControlProvider.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/controls/CompositeSpanControlProvider.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/util/Prioritized.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/controls/CompositeSpanControlProviderTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/util/PrioritizedSetTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/util/PrioritizedTest.kt
Offer a centralized interface for abstract span access where the `Span` objects may not be directly reachable.
Introduced `SpanQuery` and `SpanControlProvider` that can be implemented to fulfil various types of span access.
Implemented a `CompositeSpanControlProvider` that keeps a prioritized list of `SpanControlProvider`s and queries each of them in order, offering an easy single point of access to several providers at once.
Added the `BugsnagPerformance.getSpanControls` function to allow centralised access to any known `SpanControlProviders`, avoiding the need to directly reference any single `SpanControlProvider`. `SpanControlProvider` objects are not required to be registered like this, and could still be used instance-by-instance as well.
New unit tests were added for the …
> Introduce SpanControlProviderr

- scripts/docker-publish.sh
Ensure that the `publish` step on CI can close the staging repository using the `ossrh-staging-api`. I have also reworked the script for best practices.
Tested [here](https://buildkite.com/bugsnag/bugsnag-android-performance/builds/3056/steps?sid=01971b1b-e26f-4e47-a896-8a1439e42937#01971b1b-e89b-4228-ad9a-c77deba5cd5b/264-269) (error is the result of the versions already existing)
> Update Sonatype Release Script

- CHANGELOG.md
- bugsnag-android-performance-impl/src/testFixtures/java/com/bugsnag/android/performance/test/TestTimeoutExecutor.java
- bugsnag-plugin-android-performance-named-spans/src/main/kotlin/com/bugsnag/android/performance/controls/NamedSpanControlProvider.kt
- bugsnag-plugin-android-performance-named-spans/src/test/kotlin/com/bugsnag/android/performance/controls/NamedSpanControlProviderTest.kt
Avoid holding span references in the `NamedSpanControlsPlugin` when the span tracking stops due to the span being overwritten (when multiple concurrent spans have the same name).
New unit test
> Cancel timeouts from duplicate spans
