bugsnag/bugsnag-android-performance

- examples/performance-example/app/build.gradle
- examples/performance-example/app/src/main/java/com/example/bugsnag/performance/MainActivity.kt
- examples/performance-example/app/src/main/res/layout/activity_main.xml
- examples/performance-example/settings.gradle
Change BugSnag module references in example app to use JitPack, whille we are in Preview.  Also added a "Custom span" button.
> Example app tweaks

- Makefile
`make bump` should update the version of the SDK used by the example app
> 'make bump' should update the version used by the example app

- features/steps/performance_steps.rb
Remove unused Cucumber step.
Covered by CI.
> Remove unused Cucumber step

- features/server_response.feature
Fixes the build following a change to a step in Maze Runner `integration/v8`.
Covered by CI.
> Respond to change in Cucumber step

- Gemfile
- Gemfile.lock
- docker-compose.yml
Upgrade to Maze Runner v8.
Covered by CI.
> Upgrade to Maze Runner v8

- examples/performance-example/app/src/main/java/com/example/bugsnag/performance/LoadingActivity.kt
- examples/performance-example/app/src/main/res/layout/activity_loading.xml
- examples/performance-example/app/src/main/res/values/strings.xml
Changed the loading activity to display a "Close" button instead of simply closing. Also added an additional "loading" span which starts within the "resume" phase but ends outside of it.
Manually tested.
> Minor update to the example app

- examples/performance-example/app/build.gradle
- examples/performance-example/settings.gradle
- scripts/bump-version.sh
Fixed the version bump script to correctly update the example project dependencies
Manually tested
> Fixed the version bump script for Maven Central

- .github/ISSUE_TEMPLATE/A.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/support.md
Updating Android performance issue templates.
> [SUP-3154] Automated adjustment of repository templates

- README.md
> docs(readme): remove preview content

- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/test/OtelValidator.kt
- bugsnag-android-performance/src/test/resources/json_schema4.json
Remove the unit test silent dependency on `http://json-schema.org/draft-04/schema` which is causing timeouts.
Added a local copy of schema4 to the unit test resources.
Unit tests will pass and not timeout.
> Remove dependency on remote json schema

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanFactory.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/AppStartTest.kt
- features/instrumentation.feature
- features/nested_spans.feature
Span name shows android `AppStart/Android<type>`
Platform name added in to span name
Existing tests
> Sync span name with iOS

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/ActivityControl.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/PerformanceConfiguration.kt
Implement the annotations and changes to the instrumentation configuration
Added custom annotation classes and properties for the changes
> Implement the annotations and changes to the instrumentation configuration

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/ImmutableConfig.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/InstrumentedAppState.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/instrumentation/ActivityLifecycleInstrumentation.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/AutoInstrumentationCacheTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/ResourceAttributesTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/instrumentation/ActivityLifecycleInstrumentationTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/instrumentation/LegacyActivityInstrumentationTest.kt
Check instrumentation cache before starting view load in an activity
Added checks for instrumentation cache before starting view load
Existing unit tests and new unit tests
> Check auto instrumentation cache before starting view load for an activity

- bugsnag-plugin-android-performance-appcompat/src/main/kotlin/com/bugsnag/android/performance/AppCompatModule.kt
- bugsnag-plugin-android-performance-appcompat/src/main/kotlin/com/bugsnag/android/performance/FragmentActivityLifecycleCallbacks.kt
- bugsnag-plugin-android-performance-appcompat/src/test/kotlin/com/bugsnag/android/performance/FragmentActivityLifecycleCallbacksTest.kt
Check instrumentation cache before starting view load in a fragment
Added checks for instrumentation cache before starting view load
Existing unit tests
> Check auto instrumentation cache before starting view load for an fragment

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/ActivityControl.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/AutoInstrumentationCache.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/AutoInstrumentationCacheTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/instrumentation/LegacyActivityInstrumentationTest.kt
- bugsnag-plugin-android-performance-appcompat/src/test/kotlin/com/bugsnag/android/performance/FragmentActivityLifecycleCallbacksTest.kt
Rename DoNotInstrument annotation to DoNotAutoInstrument
Existing tests
> Rename DoNotInstrument annotation to DoNotAutoInstrument

- .buildkite/pipeline.yml
- docker-compose.yml
- dockerfiles/Dockerfile.android-common
- dockerfiles/Dockerfile.android-publisher
- docs/RELEASING.md
- scripts/docker-publish.sh
Align the release process more closely with `bugsnag-android` using BuildKite
Manually tested release
> Formalize release process with BuildKite

- .buildkite/pipeline.yml
Refines the approach in #198 by using the more succinct form of options now available in Maze Runner.
Covered by CI.
> Use specific capability options added to MR

- features/instrumentation.feature
Skip tests pending test fixture correction in PLAT-11382.
Covered by CI.
> Skip tests pending test fixture correction

- features/server_response.feature
Removed flaky end to end test scenario
> Fix scenario no p update fail retriable, fail permanent, success

- .buildkite/pipeline.yml
Move to the macOS 14 build servers.
Covered by CI.
> Use macOS 14 on CI

- features/server_response.feature
Span end to end test expectations alignment
Reviewed the tests logic and made the tests match expectations
Existing tests
> Span test expectations alignment

- bugsnag-plugin-android-performance-okhttp/src/main/kotlin/com/bugsnag/android/performance/okhttp/BugsnagPerformanceOkhttp.kt
Using `SpanTracker` in tracking network spans with calls
Replace `ConcurrentHashMap` with `SpanTracker` in the `BugsnagPerformanceOkhttp`
Existing tests
> Replace ConcurrentHashMap with SpanTracker

- features/manual_spans.feature
- features/okhttp_spans.feature
- features/server_response.feature
- features/server_response_pvalue.feature
- features/steps/performance_steps.rb
Updated span-level tests with less order-specific steps
Replace  JSON-Path checks with less order-specific steps in span_level tests
Existing tests (updated)
> Span end to end tests use new steps

- .buildkite/pipeline.yml
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/LegacyNetworkTypeTest.kt
- bugsnag-plugin-android-performance-compose/build.gradle.kts
- bugsnag-plugin-android-performance-compose/detekt-baseline.xml
- bugsnag-plugin-android-performance-compose/src/main/java/com/bugsnag/android/performance/compose/ValueContainer.kt
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
Add measured composable for measuring viewload spans
Kotlin, AGP, compose, kotlinCoroutines, gradle version bump
> Add measured composable

- bugsnag-plugin-android-performance-compose/gradle.properties
- examples/performance-example/app/build.gradle
- examples/performance-example/app/src/main/java/com/example/bugsnag/performance/LoadingActivity.kt
- examples/performance-example/app/src/main/java/com/example/bugsnag/performance/MainActivity.kt
Add MeasuredComposable in example app
Use MeasuredComposable in setContent for each Activities
Manual test
> Add MeasuredComposable in example app

- features/server_response.feature
Reduce the number of test flakes.
Changed the server_response feature to more closely match the actual behavior of the SDK
> Adjusted the server_response tests to reduce flakes

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/PerformanceConfiguration.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/SpanEndCallback.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/ImmutableConfig.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/internal/ResourceAttributesTest.kt
Users are able to add or remove spanEndCallback
Added add and remove open api for spanEndCallback
> Add and remove spanEndCallbacks

- .buildkite/pipeline.yml
Allows us to remove the v2 flakes inherent to appium v2.
> Set appium to v1 to remove v2 flakes

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/AttributesJson.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/SpanImpl.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/SpanJsonTest.kt
Log warning when the value for setting custom attribute is invalid
Adding Logger to log warning when setting custom attribute to null or unknown typs
Introduce new unit test
> warning when custom attribute value is invalid

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/framerate/FramerateMetricsSource.kt
- features/frame_metrics.feature
Correct the rendering metrics attribute names:
- ﻿bugsnag.rendering.total_frames
- bugsnag.rendering.slow_frames
- bugsnag.rendering.frozen_frames
Updated end to end tests
> Correct the rendering attributes

- .github/workflows/signing.yml
Adds a workflow for signing and uploading signatures for all release assets.
> Add signing workflow for release assets

- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/ViewLoadPhase.kt
- bugsnag-plugin-android-performance-compose/src/main/java/com/bugsnag/android/performance/compose/MeasuredComposable.kt
Compose Draw spans are ViewLoad Phase Spans
Using ViewLoadPhaseSpan for compose draw spans
Manual testing
> Compose Draw spans named ViewLoadPhase

- CODEOWNERS
- README.md
- SECURITY.md
Docs updates after OpenSSF work
> docs: add security and openssf badge

- .github/workflows/scorecard.yml
Gradle wrapper validation check
> gradle wrapper validation check

- .github/workflows/codeql.yml
> Enable CodeQL scanning

- .buildkite/pipeline.yml
Add testing on Android 15.
Covered by CI.
> Add testing on Android 15

- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/ContextAwareScheduledThreadPoolExecutorTest.kt
- bugsnag-android-performance/src/test/java/com/bugsnag/android/performance/ContextAwareThreadPoolExecutorTest.kt
Reduce the possibility of JVM unit test flakes for the thread pool tests.
Changed the tests to use (misuse?) a `SynchronousQueue` in order to synchronize the creation of spans with the expectations of the unit test.
> JVM test fixes

- CHANGELOG.md
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/metrics/CpuMetricsSource.kt
- bugsnag-android-performance/src/main/kotlin/com/bugsnag/android/performance/internal/processing/JsonTraceWriter.kt
- features/device_metrics.feature
Correctly report CPU aggregate metrics against the expected attribute names.
Updated tests to match the correct attribute names
> Fix the CPU metrics attributes

- .buildkite/pipeline.benchmark.yml
- .buildkite/pipeline.yml
Add automatic retries to Appium steps for the exit code 103
Covered by CI
> Add retries to Appium steps

- .buildkite/pipeline.benchmark.yml
- .buildkite/pipeline.yml
- .buildkite/pipeline_trigger.sh
Add benchmarking pipeline triggers
Tested by manually triggering a benchmarking build with a commit message
> Add benchmarking pipeline triggers

- .buildkite/pipeline.yml
Upload the built release artifacts to Buildkite
Will need to be tested as part of a release
> Upload release artifacts
